version: '3.8'
services:
  projectlinker-mysql:
    image: mysql:latest
    container_name: projectlinker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projectlinker
      MYSQL_USER: projectlinker
      MYSQL_PASSWORD: projectlinker
      TZ: Asia/Seoul
    command: [ "--character-set-server=utf8mb4" ]
    ports:
      - "3306:3306"
    networks:
      - projectlinker-network
  projectlinker-adminer:
    image: adminer:latest
    container_name: projectlinker-adminer
    environment:
      ADMINER_DEFAULT_SERVER: projectlinker-mysql
    ports:
      - "18080:8080"
    networks:
      - projectlinker-network
  projectlinker-redis:
    image: redis:latest
    container_name: projectlinker-redis
    ports:
      - "6379:6379"
    networks:
      - projectlinker-network
networks:
  projectlinker-network:
    driver: bridge